CREATE TABLE IF NOT EXISTS triage_sessions (
    patient_id BIGINT PRIMARY KEY,
    age_at_triage INT,
    heart_rate_bpm INT,
    resp_rate_bpm INT,
    systolic_bp INT,
    diastolic_bp INT,
    temperature_c NUMERIC(4,1),
    spo2_percent INT,
    fasting_glucose_mg_dl INT,
    total_cholesterol_mg_dl INT,
    weight_kg NUMERIC(5,1),
    height_cm NUMERIC(5,1),
    bmi NUMERIC(4,1),
    pain_level INT,
    mental_status VARCHAR(50),
    symptom_duration_days INT,
    patient_notes TEXT,
    doctor_notes TEXT,
    risk_score NUMERIC(5,4),
    risk_level VARCHAR(20),
    feature_importance TEXT[], 
    triage_urgency VARCHAR(20),
    primary_system_affected VARCHAR(50),
    symptom_progression VARCHAR(20),
    recommended_action VARCHAR(50),
    distress_level INT,
    potential_diagnosis_category TEXT,
    status VARCHAR(20) DEFAULT 'Completed',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);